config/routes.rb
Rails.application.routes.draw do

  resources :comments
  resources :users
  root "welcome#home"
  get "about" => "welcome#about"

  resources :articles

  get 'signup' => 'users#new'
  post 'users' => 'users#create'
  resources :users, except: [:new]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 30 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  has_many :comments

  before_save { self.email = email.downcase }

  validates :username, presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true,
            length: { maximum: 105 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  #sert a donner accès a une méthode en précisant les méthodes qui pourront l'utiliser
  before_action :set_article, only: [:edit, :update, :show, :destroy]

  def index
    @articles = Article.all
  end

  def edit

  end

  def new
    @article = Article.new
  end

  def create
    #debugger
    #render plain sert a attraper et afficher les params envoyé dans l'url a la creation
    # render plain: params[:article].inspect
    @article = Article.new(article_params)
    #seul moyen de définir a la creattion d'un article qu'il doit détenir a un user
    @article.user = User.first

    #Si article bien sauvegarder alors... sinon
    if @article.save
      flash[:success] = "Article was succesfully created"
      #redirige sur page de l'article
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update

    if @article.update(article_params)
      flash[:success] = "Article was sussessfully updated"
      redirect_to article_path(@article)
    else
      render "edit"
    end
  end

  def show

  end

  def destroy
    @article.destroy
    flash[:danger] = "Article was successfully deleted"
    redirect_to articles_path
  end

#Factorisation de code récurrent
  private
    #cf before_action qui définit les méthodes qui auront accès a cette méthode
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      #défini les params de l'article
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:description, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "Welcome to the alpha blog #{@user .username}"
      redirect_to articles_path
    else
      format.html { render :new }
    end
    end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password_digest)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home

  end

  def about
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= render "shared/errors", obj: @article%>

    <div class="row">
      <div class="col-md-12">
        <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |a| %>
        <div class="form-group row">
          <div class="col-form-label col-sm-1">
            <%= a.label :title %><br/>
          </div>
          <div class="col-sm-10 col-sm-1">
            <%= a. text_field :title, class: "form_control", placeholder: "Title of article", autofocus: true %>
          </div>

        </div>
          <div class="form-group row">
            <div class="col-form-label col-sm-1">
          <%= a.label :description %>
            </div>
            <div class="col-sm-10 col-sm-1">
          <%= a.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
            </div>
      </div>
          <div class="form-group">
            <div class="col-sm-10 offset-sm-1">
            <%= a.submit class: "btn btn-primary btn-block"%>
            </div>
    </div>


        <% end %>
        <div align="center">
       [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
        </div>
      </div>
    </div>

app/views/articles/edit.html.erb
<h1 align="center">Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align=""center>Listing all articles</h1>
<p>
  <%= link_to "Create new article", new_article_path %> | <%= link_to "Back home", root_path %>
</p>

<% @articles.each do |article| %>
  <div class="card text-center">
    <div class="card-header">
      Article
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= link_to article.title, article_path(article) %></h5>
      <p class="card-text"><%= truncate(article.description, length: 100) %></p>
        <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
        <%= link_to "Delete this article", article_path(article), method: :delete,
                  data: { confirm: "Are you sure you want to delete the article?"},
                  class: "btn btn-xs btn-danger" %>
    </div>
    <div class="card-footer text-muted">
      <small>Created by: <%= article.user.username if article.user %>,
        <%= time_ago_in_words(article.created_at)  %> ago,
        last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
    </div>
  </div>
  <br>
<% end %>

app/views/articles/new.html.erb
<h1 align="center">Signup for alpha blog</h1>


<%= render 'form' %>

app/views/articles/show.html.erb
<div class="card text-center">
  <div class="card-header">
    <h2 align="center">Title: <%= @article.title %></h2>
  </div>
  <div class="card-body">
    <h5 class="card-title description"><strong>Description:</strong></h5>
    <p class="card-text"><%= simple_format(@article.description) %></p>
    <div class="article-actions">
    <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-primary" %> |
      <%= link_to "Delete this article", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete the article?"}, class: "btn btn-danger" %> |
    <%= link_to "View all articles", articles_path, class: "btn btn-success" %>
  </div>
  </div>
  <div class="card-footer text-muted">
    <small>Created by: <%= @article.username if @article.user %>,
      <%= time_ago_in_words(@article.created_at)  %> ago,
      last updated: <%= time_ago_in_words(@article.updated_at) %> ago</small>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.description %></td>
        <td><%= comment.user_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @comment.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_footer.html.erb
<div class="container-fluid">
  <footer class="footer">
    <small>
      Copyright &copy: <a href="https://www.linkedin.com/in/dorian-maillard-91050211a/">The Complete Ruby on Rails Developer</a>
      by <a href="https://www.linkedin.com/in/dorian-maillard-91050211a/">Dodoma95</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
  <div class="row">
    <div style="width:100%;">
      <%= flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>' role="alert">
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
  <% end %>
    </div>
  </div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <%= link_to "Alpha blog", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Articles", articles_path, class:"nav-link", id: "articles" %>
        <!--<a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>-->
      </li>
      <li class="nav-item dropdown active">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Actions
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "New Article", new_article_path, class:"dropdown-item" %>
          <!--<a class="dropdown-item" href="#">Action</a>-->
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search some article" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container-fluid">
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row col-md-10 offset-1">
    <div class="col-xs-8 offset-2">
      <div class="card border-danger mb-3">
        <div class="card-header">
          <h2 class="card-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this article from being saved:
          </h2>
          <div class="card-body text-danger">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, class: "form-control", placeholder: "Enter email" %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password_digest, rows: 10, class: "form-control", placeholder: "Enter password" %>
  </div>

  <div class="actions">
    <%= form.submit "Sign up", class: "btn btn-primary btn-block"%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1 align="center">Signup for Alpha Blog</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/about.html.erb
<h1>Welcome to my about page</h1>

<%= link_to "Home", root_path %>

app/views/welcome/home.html.erb
<div class="center jumbotron">
  <h1>ALPHA BLOG</h1>
  <%= link_to "Sign up now", "#", class: "btn btn-danger btn-lg btn-xlarge"%>
</div>